version: "3.3"

services:
  ts-monorepo-app:
    env_file: .env
    container_name: ts-monorepo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    extra_hosts:
      - "localhost:host-gateway"
